# HTML5 Template Project
# author: Andras Csizmadia <andras@vpmedia.hu>

git:
  depth: 1

language: node_js
node_js:
  - '6'

env:
  - TERM=dumb

script:
  - yarn run lint
  - yarn run flow
  - yarn run test
  - yarn run webpack-lib
  - yarn run webpack
