// flow-typed signature: 04e743c978f01f17efafdba93e842895
// flow-typed version: <<STUB>>/babel-polyfill_v^6.20.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-polyfill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-polyfill' {
  declare module.exports: any;
}
