// flow-typed signature: cc6bc785d9cb499fae91bc1a64f9e2f3
// flow-typed version: <<STUB>>/phaser-ce_v^2.7.3/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'phaser-ce'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'phaser' {
  declare module.exports: any;
}
