// flow-typed signature: 60f27aca45d18873eb15e3dc8b327034
// flow-typed version: <<STUB>>/promise-polyfill_v^6.0.2/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'promise-polyfill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'promise-polyfill' {
  declare module.exports: any;
}
